#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/opt/conda/envs/py27"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/opt/conda/envs/py27/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/yazanb/allensdk/doc_template/examples/nb/friday_harbor/components/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
